### ISSUE TITLE
wrong rendering order when child route being called before parent route

### ISSUE THREAD

**Issue by mnifakram** [ef4/ember-elsewhere#21]
let's say that I have an `admin` route and underneath it an `org` route and I want to show a different side bar for each one.
If the user go to `/admin` it will show the **admin** side bar, then proceeding to `/admin/org` also will show the **org** side bar.

But if the user hit `/admin/org` directly then this will cause an order issue and shows the **admin** side bar instead of the **org** sidebar 

To reproduce the error try to navigate from the root route `/` to `/admin/org` directly
 https://ember-twiddle.com/c55403cfe94847c995f6dabf5fb502c2?route=%2Fadmin%2Forg

**Comment by NullVoxPopuli** [comment]
The {{outlet}} in admin/template should be after the to-elsewhere invocation :-)
