### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by cbou** [ef4/ember-elsewhere#22]
Elsewhere seems to have a memory leak.

You can reproduce the error by opening this page: https://ef4.github.io/ember-elsewhere/

Then run `queryObjects(HTMLElement)` in the JavaScript console or use the new Performance Monitor feature of Google Chrome.

The number of DOM Node will grow after each click on "First Page", "Second Page" or "Third Page".

<img width="359" alt="screen shot 2018-01-25 at 23 02 40" src="https://user-images.githubusercontent.com/611389/35414809-ea9e20ec-0223-11e8-8f40-bbfb0ba9e52c.png">
<img width="343" alt="screen shot 2018-01-25 at 23 02 45" src="https://user-images.githubusercontent.com/611389/35414810-eab7419e-0223-11e8-93ee-2a107265ab0f.png">

**Comment by erichonkanen** [comment]
has anyone looked at this? this is very troubling if true considering how invested in elsewhere I am in my app

**Comment by cbou** [comment]
Still an issue. Any chance it will be investigate?

**Comment by cbou** [comment]
Actually it's not an issue. Using queryObjects retains the objects within the console that's why the array is growing. Switching between second and third a couple of time without printing `queryObjects` does not show a big growth.
