### ISSUE TITLE
Portal from one component to another

### ISSUE THREAD

**Issue by adambedford** [ef4/ember-elsewhere#23]
Is it possible to portal content from one component to another? I'm not seeing the content show up in the from-elsewhere placeholder

**Comment by adambedford** [comment]
Figured this out. The issue was a typo in my implementation. The `{{from-elsewhere}}` component takes an attribute `name`, however the `{{to-elsewhere}}` component take an attribute `nameD`

**Comment by ef4** [comment]
Sorry. You're not the only one. The parameters are empirically bug magnets.

I just pushed fef99e9759e06fa868c41e612d849a4c75d4a168 to hopefully save the next person's debugging time.
