### ISSUE TITLE
Cannot use 'attributeBindings' on a tag-less component.

### ISSUE THREAD

**Issue by phcoliveira** [ef4/ember-elsewhere#3]
Hello there.

I don't know what am I doing wrong. I've been trying to use component `from-elsewhere` in both forms: inline and as a block, but ember complains about this error:

```ember.debug.js:19087 Uncaught Error: Assertion Failed: You cannot use `attributeBindings` on a tag-less component: <cuscuz@component:from-elsewhere::ember1030>```

I am not doing any further customizations with the component, I'm just passing "modal" for the name option.

Also, I'm using Ember 2.8.0 and removed Liquid Fire.

**Comment by ef4** [comment]
Maybe you're also using ember-hammertime? It has [a known bug](https://github.com/runspired/ember-hammertime/issues/19#issuecomment-249865762) that will trigger that message any time you have a tagless component, and ember-elsewhere introduces tagless components.

**Comment by phcoliveira** [comment]
Yep, you are absolutely right. I am sorry for troubling you with this, but I would never guess it was some other addon. Anyway, maybe this issue can help somebody else.

Thanks for your readiness.

**Comment by ef4** [comment]
Yeah, I think this issue will help others who are searching for that message. :-)
