### ISSUE TITLE
Switch to {{in-element}}

### ISSUE THREAD

**Issue by sandstrom** [ef4/ember-elsewhere#37]
Would it make sense for this addon to switch to `{{in-element}}`?

https://github.com/emberjs/ember.js/pull/18867

Trying to understand whether this addon does more things, that aren't supported by `{{in-element}}`.

**Comment by ef4** [comment]
I think in-element errors if the target doesn't exist? An important thing this addon does is let you render the source and destination in any order relative to each other.

**Comment by sandstrom** [comment]
Alright, that makes sense!
