### ISSUE TITLE
Render multiple components into one placeholder

### ISSUE THREAD

**Issue by addmitriev** [ef4/ember-elsewhere#5]
Render multiple components into one placeholder. Is it possible to do it?
Like this:

```
{{to-elsewhere named="top-container" send=(component "first-component")}}
{{to-elsewhere named="top-container" send=(component "second-component")}}
```

Now it just replacing one to another

**Comment by ef4** [comment]
It's not currently supported. This is a feature we can add if somebody wants to work on it.

I would suggest adding a new component like `multiple-from-elsewhere` that would be used in place of `from-elsewhere` when you want multiple values. This will also require a slight refactoring of the service so the values in `actives` are ordered lists, not just the most recent for each name.

**Comment by addmitriev** [comment]
@ef4 Thank you for your response. I think it should be a new service and components with `multiple` prefix or without such one. But in the second case we should rewrite current components. The problem is that I don't understand how to refactor current service to support `multiple-from-elsewhere` component without rewriting [this line](https://github.com/ef4/ember-elsewhere/blob/master/addon/services/ember-elsewhere.js#L33). If I do that it would break current logic.

**Comment by ef4** [comment]
Yes, I think we can just make a small change to the existing `from-elsewhere` from:

```hbs
(get (get service.actives name) 'component')
```

to

```hbs
(get (get service.actives name) 'lastObject.component')
```

**Comment by utilityboy** [comment]
This would be a very nice addition.  I can try to find time to work something up if you haven't already  @addmitriev

**Comment by addmitriev** [comment]
@utilityboy It will be great. I have no to implement it now. Looking forward for your PR! 🍭

**Comment by vladucu** [comment]
@utilityboy I would also be really interested in this....did you ever found time for it?
If not, I might try to look into it

**Comment by utilityboy** [comment]
@addmitriev / @vladucu Let me try to find time this week.  @addmitriev I totally missed your comment from November.
