### ISSUE TITLE
Fix deprecation this-property-fallback

### ISSUE THREAD

**Issue by cah-briangantzler** [ef4/ember-elsewhere#51]
add this to the local properties being used in the hbs

**Comment by cah-briangantzler** [comment]
Any change of getting this merged?

**Comment by ef4** [comment]
Thanks, merged and released as 1.2.2.

**Comment by cah-briangantzler** [comment]
Thanks, working on one for ember-cli-babel, but may have to do more than that to get rid of linting and such. May have to make min ember 3.8 to update ember-cli-htmlbars, hope that is ok

**Comment by ef4** [comment]
Yes, that would be ok.
