### ISSUE TITLE
Unable to create a pull request

### ISSUE THREAD

**Issue by cah-briangantzler** [ef4/ember-elsewhere#55]
When attempting to create a PR I am getting the following not very detailed error. Anyone have any ideas?

![image](https://user-images.githubusercontent.com/1529286/141806484-a131ec67-865a-4dda-b040-45cfcd9c7ca2.png)

**Comment by ef4** [comment]
Seems like a GitHub bug. We don't have any interesting settings that would prevent PRs.

**Comment by ef4** [comment]
If you're still seeing this, can you please submit a support ticket to GitHub?

https://support.github.com/contact

**Comment by cah-briangantzler** [comment]
This was my stupid mistake. This is an old repo and I forgot to authorize my work account to create PRs off the repo that was forked as a personal account.
