### ISSUE TITLE
ember-elsewhere retaining memory

### ISSUE THREAD

**Issue by tim-evans** [ef4/ember-elsewhere#6]
Hey there!

We've been debugging our app, trying to pin down a memory leak that's been causing our test suite to crash occasionally. I've tracked down some of the retained memory to ember-elsewhere's service, which is holding onto components after the app has been torn down.

I used Chrome's allocation timeline to collect information about what objects are retaining data in our app's test suite. The results put ember-elsewhere at the top of the list of retained objects:

![screen shot 2016-10-25 at 4 05 49 pm](https://cloud.githubusercontent.com/assets/177701/19702327/0cc92f00-9acd-11e6-939f-18cb957cdb30.png)
![screen shot 2016-10-25 at 4 05 58 pm](https://cloud.githubusercontent.com/assets/177701/19702321/040c99e2-9acd-11e6-9ebb-939fef4b92fb.png)
![screen shot 2016-10-25 at 4 06 11 pm](https://cloud.githubusercontent.com/assets/177701/19702323/061497f8-9acd-11e6-8dd6-0fe43bd0f0b2.png)

I experimented with cleaning up after the `ember-elsewhere` service with the following patch:

```js
import Ember from 'ember';
import EmberElsewhere from 'ember-elsewhere/services/ember-elsewhere';

export default EmberElsewhere.extend({
  destroy() {
    this._alive = {};
    this._super();
    Ember.run.later(this, () => {
      delete this.actives;
    }, 100);
  }
});
```
![screen shot 2016-10-25 at 4 06 20 pm](https://cloud.githubusercontent.com/assets/177701/19703220/00997646-9ad1-11e6-862f-5d774f5d4af8.png)

And `ember-elsewhere` dropped off from the retained objects graph (see that `Class` moved from the top position to the 3rd position, releasing ~79Mb of memory in the process).

I don't think my approach is the ideal approach to this problem, but would love to see this fixed! Thanks for the wonderful addon @ef4, and if you want more information, let me know so I can provide enough context on this.

Cheers!

**Comment by ef4** [comment]
Thanks, nice investigation.

I don't fully understand yet why this leaks, but it's clear that it does.

**Comment by ef4** [comment]
If I am reading your screenshots correctly, I think you have a closure causing the whole container to be retained. The container retains the ember-elsewhere service, and the service retains components. Cutting the link between the service and components frees some of the memory, but would still allow the rest of the container to leak.

I would investigate the `-mouse-hover` service first. If it has a global event handler installed that closes over itself, that would explain this whole behavior.

**Comment by tim-evans** [comment]
Haha, that's what I found, and it was the big memory leak. Thanks!

**Comment by tim-evans** [comment]
And that's quite amazing that you were able to pin down our app's memory leak from this screenshot!

**Comment by ef4** [comment]
😎
